---
- name: Converge
  hosts: all
  connection: local
  vars:

  tasks:
    - name: Load Scenario Variables
      include_vars: vars/main.yml
    - name: "Include osx_provisioner.role_downloader"
      ansible.builtin.include_role:
        name: "osx_provisioner.role_downloader"
